// --- Módulo de Elementos del DOM ---
// Centraliza todas las referencias a los elementos HTML para un acceso fácil y organizado.

export const DOM = {
    appContainer: document.querySelector('.app-container'),
    welcomeScreen: document.getElementById('welcome-screen'),
    dropZone: document.getElementById('drop-zone'),
    imageLoader: document.getElementById('image-loader'),
    imageDisplay: document.getElementById('image-display'),
    canvas: document.getElementById('measurement-canvas'),
    rulerTop: document.getElementById('ruler-top'),
    rulerLeft: document.getElementById('ruler-left'),
    imageDimensionsP: document.getElementById('image-dimensions'),
    framesList: document.getElementById('frames-list'),
    rowsInput: document.getElementById('rows-input'),
    colsInput: document.getElementById('cols-input'),
    cellWInput: document.getElementById('cell-w-input'),
    cellHInput: document.getElementById('cell-h-input'),
    generateGridButton: document.getElementById('generate-grid-button'),
    generateBySizeButton: document.getElementById('generate-by-size-button'),
    clearButton: document.getElementById('clear-button'),
    previewCanvas: document.getElementById('preview-canvas'),
    playPauseButton: document.getElementById('play-pause-button'),
    firstFrameButton: document.getElementById('first-frame-button'),
    lastFrameButton: document.getElementById('last-frame-button'),
    fpsSlider: document.getElementById('fps-slider'),
    fpsValue: document.getElementById('fps-value'),
    undoButton: document.getElementById('undo-button'),
    redoButton: document.getElementById('redo-button'),
    clipsSelect: document.getElementById('clips-select'),
    newClipButton: document.getElementById('new-clip-button'),
    renameClipButton: document.getElementById('rename-clip-button'),
    deleteClipButton: document.getElementById('delete-clip-button'),
    selectAllFramesButton: document.getElementById('select-all-frames'),
    deselectAllFramesButton: document.getElementById('deselect-all-frames'),
    changeImageButton: document.getElementById('change-image-button'),
    toast: document.getElementById('toast'),
    projectHistoryList: document.getElementById('project-history-list'),
    lockFramesButton: document.getElementById('lock-frames-button'),
    fullscreenButton: document.getElementById('fullscreen-button'),
    exportZipButton: document.getElementById('export-zip-button'),
    exportGifButton: document.getElementById('export-gif-button'),
    maxGifSizeInput: document.getElementById('max-gif-size'),
    exportCodeButton: document.getElementById('export-code-button'),
    codeExportDetails: document.getElementById('code-export-details'),
    codePreviewContainer: document.getElementById('code-preview-container'),
    htmlCodeOutput: document.getElementById('html-code-output'),
    cssCodeOutput: document.getElementById('css-code-output'),
    htmlLineNumbers: document.getElementById('html-line-numbers'),
    cssLineNumbers: document.getElementById('css-line-numbers'),
    livePreviewIframe: document.getElementById('live-preview-iframe'),
    jsonOutput: document.getElementById('json-output'),
    jsonFormatSelect: document.getElementById('json-format-select'),
    jsonLineNumbers: document.getElementById('json-line-numbers'),
    autoDetectButton: document.getElementById('auto-detect-button'),
    autoDetectToleranceInput: document.getElementById('auto-detect-tolerance'),
    exportScaleInput: document.getElementById('export-scale-input'),
    selectToolButton: document.getElementById('select-tool-button'),
    createFrameToolButton: document.getElementById('create-frame-tool-button'),
    eraserToolButton: document.getElementById('eraser-tool-button'),
    autoDetectToolButton: document.getElementById('auto-detect-tool-button'),
    removeBgToolButton: document.getElementById('remove-bg-tool-button'),
    editorArea: document.getElementById('editor-area'),
    imageContainer: document.getElementById('image-container'),
    zoomOutButton: document.getElementById('zoom-out-button'),
    zoomInButton: document.getElementById('zoom-in-button'),
    zoomFitButton: document.getElementById('zoom-fit-button'),
    zoomDisplay: document.getElementById('zoom-display'),
    subframePropsPanel: document.getElementById('subframe-props-panel'),
    subframeIdDisplay: document.getElementById('subframe-id-display'),
    subframeOffsetXInput: document.getElementById('subframe-offset-x'),
    subframeOffsetYInput: document.getElementById('subframe-offset-y'),
    loadingOverlay: document.getElementById('loading-overlay'),
    allControls: document.querySelectorAll('button, input, select'),
};

// Centralizamos también los contextos de los canvas
export const CTX = {
    main: DOM.canvas.getContext('2d'),
    rulerTop: DOM.rulerTop.getContext('2d'),
    rulerLeft: DOM.rulerLeft.getContext('2d'),
    preview: DOM.previewCanvas.getContext('2d'),
};